version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: distribuidora_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secretroot
      MYSQL_DATABASE: distribuidora_cheles
      MYSQL_USER: chelesuser
      MYSQL_PASSWORD: chelesdb
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_distri_cheles_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-psecretroot"]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin:5-apache
    container_name: distribuidora_phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      UPLOAD_LIMIT: 256M
    depends_on:
      - mysql

volumes:
  mysql_distri_cheles_data:
